name: CI/CD Pipeline

on:
  pull_request:        # Trigger for PR
    branches:
      - main
  push:                # Trigger for merge (push to main)
    branches:
      - main

env:
  APP_VERSION: 5.0.0

jobs:

  # 🔨 Build & Push on PR
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub manually
        run: docker login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build image
        working-directory: ./application # Switch to app folder
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:$APP_VERSION .

      - name: Push image
        working-directory: ./application # Switch to app folder
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:$APP_VERSION

  # 🚀 Deploy on Merge to main
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Print message
        run: echo "Hello Suresh, CI/CD is working!"   # Step

      