# Github Action Offical Documentation
# https://docs.github.com/en/actions/concepts/workflows-and-actions/workflows
# https://docs.github.com/en/actions

name: Simple CI Pipeline   # Workflow

on: [push]                # Event (trigger)

jobs:
  build:                  # Job
    runs-on: ubuntu-latest   # Runner - https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Action

      - name: Print message
        run: echo "Hello Suresh, CI/CD is working!"   # Step